name: 'Build and Test'
on:
  pull_request:
  workflow_dispatch:
  push:
    branches:
      - "main"

permissions: {}

jobs:  
  integration-tests:
    permissions:
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      - id: nvmrc 
        name: Extract Node.JS Version
        shell: bash
        run: |
          echo "node-version=$(cat .nvmrc)" >> "${GITHUB_OUTPUT}"
      - name: Set Node.JS
        uses: actions/setup-node@a0853c24544627f65ddf259abe73b1d18a591444 # v5.0.0
        with:
          node-version: "${{ steps.nvmrc.outputs.node-version }}"
      - id: clean-dist
        shell: bash
        run: |
          # Clean the existing dist/ folder so that we only test fresh
          # compiled code
          rm -rf dist/
      - run: |
          npm ci
      - run: |
          npm run all
